gcc-c++11:
  script: "CI/ci-linux.sh gcc C++11"
  tags:
    - Linux

clang-c++11:
  script: "CI/ci-linux.sh clang C++11"
  tags:
    - Linux

gcc-c++98:
  script: "CI/ci-linux.sh gcc C++98"
  tags:
    - Linux

clang-c++98:
  script: "CI/ci-linux.sh clang C++98"
  tags: 
    - Linux

macos-c++11:
  script: "CI/ci-mac.sh C++11"
  tags:
    - Apple
  artifacts:
    paths:
      - build-release-cpp11/*.dmg
      - build-release-cpp11/*.tar.gz

macos-c++98:
  script: "CI/ci-mac.sh C++98"
  tags:
    - Apple
  artifacts:
    paths:
      - build-release-cpp98/*.dmg
      - build-release-cpp98/*.tar.gz

cppcheck:
  script: "CI/ci-cppcheck.sh"
  tags:
    - Linux
  artifacts:
    paths:
      - cppcheck.log
